### ISSUE TITLE
Add deb2appimage binary?

### ISSUE THREAD

**Issue by EthanWeegee** [minecraft-linux/mcpelauncher-wiki#14]
There is a handy tool called [deb2appimage](https://github.com/simoniz0r/deb2appimage) that can make an AppImage binary from Ubuntu `.deb`s. I've used this tool to create a config file that can produce a working AppImage of the launcher, that you can find [here.](https://github.com/EthanWeegee/mcpelauncher-deb2appimage) This AppImage bundles `msa-daemon`, which it will run on startup, and is smaller than the currently provided AppImage. (I'm curious as to the size difference: ~90 MB vs. 11.3 MB)

**Comment by MCMrARM** [comment]
that sounds broken, are you sure you can run the resulting binary on a clean system?

**Comment by EthanWeegee** [comment]
I couldn't get it to run on a live Xubuntu 18.04 session, but it runs on another Xubuntu 18.04 install I have, and on openSUSE Leap 15 install. the live session complains that the client isn't in the PATH, but I've confirmed that it is.

**Comment by Mhowser** [comment]
Issue cleanup. I can reopen if needed.
