### ISSUE TITLE
Lan games with another dispositives like android 

### ISSUE THREAD

**Issue by mschimieguel** [minecraft-linux/mcpelauncher-wiki#18]
first, i need to say : this initiative is wonderful,i have a trouble with a Lan game,basically i cant see a friend lan world in an android MCPE  and he cant see my world in the same wifi conection. ps : I have tried with hotspot conection  with him smartphone  however  doesnt work.The multiplayer options are always  enabled.I use on lubuntu 18.04.

**Comment by Mhowser** [comment]
make sure port 19132 allows traffic on lan, check your firewall.
