### ISSUE TITLE
I can't log in to my google account

### ISSUE THREAD

**Issue by zaze06** [minecraft-linux/mcpelauncher-wiki#20]
hi when I tray to log in to mi google acont it "this browser or app may not be secure

try a different browser. if you're already using a supported browser, you can refresh your screen and try agen to sign in"
1. how do I refresh my screen
2. I'm playing on Mac OS catalina
3. the browser is supported because a YouTube video shows it
if you know how I can fix it pleas tell me

**Comment by cats824** [comment]
I have the same issue, It is caused by something that google did, not your issue, it happens on linux as well.

**Comment by zaze06** [comment]
ok can the coders fix it or something?

**Comment by cats824** [comment]
That depends I don't work on the project, google basically did something to block the application that uses the google login, so it possibly can be fixed but I don't know how long it will take or if it is easy

**Comment by jurassicjordan** [comment]
I'm also having this problem. leave it to google to ruin its own services.

**Comment by kode54** [comment]
Maybe it has something to do with the forced migration to OAuth?

**Comment by atishpatel** [comment]
Use this forked and patched version. https://github.com/ChristopherHX/mcpelauncher-manifest/releases

**Comment by Josh-East** [comment]
> Use this forked and patched version. https://github.com/ChristopherHX/mcpelauncher-manifest/releases

atishpatel,
The browser sign-on worked, but after downloading the game; I get a curl error.

Thanks.

**Comment by Cross-Prog** [comment]
> Use this forked and patched version. https://github.com/ChristopherHX/mcpelauncher-manifest/releases

atishpatel,

After using the forked version, It did let me sign on. However, after downloading the game I get a curl error, and it never lets me play. It takes me back to download the game again.

Thanks.

**Comment by Cross-Prog** [comment]
> > Use this forked and patched version. https://github.com/ChristopherHX/mcpelauncher-manifest/releases
> 
> atishpatel,
> 
> After using the forked version, It did let me sign on. However, after downloading the game I get a curl error, and it never lets me play. It takes me back to download the game again.
> 
> Thanks.

<img width="650" alt="SS" src="https://user-images.githubusercontent.com/36284826/79341799-f3292700-7ef1-11ea-9c22-d27e8696f70f.png">

**Comment by AsimoaHD** [comment]
I have the same Problem.

**Comment by Mhowser** [comment]
update the launcher and try again.
