### ISSUE TITLE
No support for macOS 10.11.6 or lower.

### ISSUE THREAD

**Issue by dadky** [minecraft-linux/mcpelauncher-wiki#27]
I'm currently running an ancient computer, i know; however, it would be amazing to be able to run your version of bed-rock edition.

I'd like support for macOS X 10.11.6 Captain.
_(For dummies, it literally doesn't open as the application doesn't support lower versions)_

Was this request moved, removed or commented on before? i haven't seen this but please redirect me to the correct place if i'm wrong/ in the wrong section for such a request.

**Comment by ChristopherHX** [comment]
I have added **theoretical** support for 10.10 and 10.11 a while ago
https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/stable/Minecraft_Bedrock_Launcher_0.0.136_macOS_10.10.0.dmg

Addition Bugs
You cannot have multiple Launcher Profiles (qt bug, newer qt needs 10.12+)
