### ISSUE TITLE
Could not find the game launcher

### ISSUE THREAD

**Issue by Rozkalns** [minecraft-linux/mcpelauncher-wiki#33]
How?
```
$ which mcpelauncher-client
/usr/local/bin/mcpelauncher-client

$ ll $(which mcpelauncher-client)
lrwxr-xr-x  1 roberts  admin    79B May 21 09:04 /usr/local/bin/mcpelauncher-client@ -> /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/mcpelauncher-client`
```
There it is. 
What am I still missing?

**Comment by ChristopherHX** [comment]
macOS Catalina?
The old wiki dmg file told you an missleading errormessage.
mcpelauncher-client exits, but is a 32bit Program and your OS has 32bit disabled.

https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#macos-x-catalina-could-not-find-the-game-launcher

Look here for a preview with a 64bit launcher, which can be executed without a downgrade to mojave or older
https://github.com/ChristopherHX/mcpelauncher-manifest/releases
