### ISSUE TITLE
Sign in with a Microsoft Account that owns Minecraft Bedrock

### ISSUE THREAD

**Issue by TakutoYo** [minecraft-linux/mcpelauncher-wiki#34]
I have a Microsoft Account that owns Minecraft Bedrock, and I was hoping I could access my copy from MCPE Launcher. However you need to own it on Google Play, but I don't. Could you make it possible to use a Microsoft Account for MCPE Launcher?

**Comment by ChristopherHX** [comment]
**Short no not possible and never will be possible.**
This is a thin 'android emulator' with small mods to have win10 like mouse input.
Can you login to microsoft in the google play store? I can't.
**This isn't an windows emulator**, like wine. You need a complete different launcher.

Related offical articles
https://help.minecraft.net/hc/en-us/articles/360042699352-Can-I-Transfer-My-Copy-of-the-Game-to-a-Different-Device-
https://help.minecraft.net/hc/en-us/articles/360042699152-Can-I-Swap-my-Version-of-Minecraft-
