### ISSUE TITLE
Error while extracting file: Filled to open zip 21

### ISSUE THREAD

**Issue by Theaxolotl228** [minecraft-linux/mcpelauncher-wiki#52]
![image](https://user-images.githubusercontent.com/89574813/146340719-76fbd528-556f-4490-8cee-8f83901bfcce.png)
i am using x86 apk and it is not archived

**Comment by ChristopherHX** [comment]
That's a modified apk, this doesn't happen with apk's downloaded directly from the google play store.

E.g. the zip format of your apk is too new for the AppImage. You can extract the apk and create a new zip of the extracted content. ~~Using another installation method like building from source can fix this.~~
