### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by GuilhermeRossato** [minecraft-linux/mcpelauncher-wiki#7]
I read the docs, I know how this works, I know how to do every step of the way, hell I can setup a docker container to compile and build this from souce and yet...

**I have absolutely no idea what the hell is this project is about.**

I'm serious. You reading this must think I'm some kind of special stupid because it is obvious to you, but to me, it is a COMPLETE MYSTERY. I want to know what the project is about but there's not even a readme here! Nowhere in the website (not even at the in the frequently asked questions) or anywhere does it say anything about what is this project about.

It is a launcher for minecraft... So, what exactly is that? Like, does it take minecraft physically and throws it at the windows? Oh, the docs mention windows is not supported, so maybe it throws it out the door? By the way doesn't minecraft launch itself? **What problem are you solving here?** Is it just to run minecraft PE in a different OS?

It feels like it's a secret project or something.

**Comment by Mhowser** [comment]
This launcher 'launches' the "Bedrock edition" or "Better Together edition" version of Minecraft on Linux and Mac OS. 2 major operating systems that Microsoft didn't bother to include. So, simply put, this launcher just runs the Android version of Bedrock Minecraft with desktop support.

If you have any more questions, please join the Discord server https://discord.gg/27TUUwf
