### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by HttpAnimation** [minecraft-linux/mcpelauncher-wiki#86]
I keep getting 
The Launcher failed to sign you in
Please login again
Failed to perform http request to https://android.clients.google.com/auth : CURLcode 35 Details: gnutls_handshake() failed: The TLS connection was non-properly terminated

when trying to sign in I used the website and the sign-in that is built in 
![image](https://github.com/minecraft-linux/mcpelauncher-wiki/assets/97435656/0aefd8e5-ec4b-47bb-ad5d-09869f8543d3)
Pop os

**Comment by WarrenOC** [comment]
Having Similar issues though mine does not say anything after please login again
Linux Mint 21.2

**Comment by KolbySisk** [comment]
I'm also seeing a similar issue. 

```
The Launcher failed to sign you in
Please login again
Login failed
```

Trying on a steam deck

**Comment by HttpAnimation** [comment]
I found my fix it was because my VPN.
