### ISSUE TITLE
Crash on clicking play;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [minecraft-linux/mcpelauncher-wiki#9]
Thought I would try this, but I get this once I signed in and downloaded MC from android;

> EGL_VERSION = 1.5
19:02:48 Trace [Launcher] Loading hybris libraries
19:02:48 Trace [HybrisUtils] Loaded OS library /usr/local/share/mcpelauncher/libs/native/libfmod.so.9.16
19:02:48 Trace [HybrisUtils] Loaded OS library libm.so.6
19:02:48 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: %sCannot load library: reloc_library[1373]:     0 cannot locate 'memalign'...
Signal 6 received
Backtrace elements: 13
#0 /usr/local/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x70) [0x567c0d4c]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f7d070]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f7d059]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf784b832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf784ccc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7ba997d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7bb10f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7bb115d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7bb145c]
#9 /usr/local/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x10e) [0x567c1c3e]
#10 /usr/local/bin/mcpelauncher-client(main+0xbaf) [0x5677c6c1]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7836e81]
#12 /usr/local/bin/mcpelauncher-client(+0x18c551) [0x5677b551]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by MCMrARM** [comment]
Wrong repo, please report here: https://github.com/minecraft-linux/mcpelauncher-manifest/issues
