### ISSUE TITLE
Stuck at “Connecting to multiplayer game” on Fedora 40 flathub package, minecraft 1.20.81

### ISSUE THREAD

**Issue by mohdyusuf** [minecraft-linux/mcpelauncher-wiki#94]
I am seeing this issue w/ latest flathub package. I tried logout, delete the package from Gnome Software center and reinstall fresh didnt work.

Minecraft version 1.20.81
Fedora 40

When I launched Android 14 emulator x86_64 (tablet) from Android studio, I was able to install, login to play store, login to Microsoft account and joined LAN game just fine. I think it may be something to do with the launcher.

**Comment by joao-pedro-alves** [comment]
Same here. It used to work few weeks ago. Now always when I try to connect a server it gets stuck at "connecting to multiplayer game"...

**Comment by mohdyusuf** [comment]
Update to latest launcher v0.15.0 (build 79) and Minecraft 1.21.x from Google play and it is now working to connect to another LAN server.
